config/routes.rb
Rails.application.routes.draw do
  
	root 'projects#index'
  	devise_for :users
  	resources :projects
  	resources :bugs do
  		member do
  			get :assign
  			get :assigned
  		end
  	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bug.rb
class Bug < ApplicationRecord
  belongs_to :creator, class_name: :User
  belongs_to :developer, class_name: :User,optional: true
  belongs_to :project
  validates :title, uniqueness: true
  mount_uploader :screenshot, ScreenshotUploader


    TYPE=['feature','bug']
	STATUS=['new','started','completed']
end

app/models/project.rb
class Project < ApplicationRecord
	has_many :project_users
	has_many :users, through: :project_users
	has_many :bugs
	accepts_nested_attributes_for :project_users,  reject_if: proc { |pu| pu['user_id'].blank? }

 #    #callback
	# after_create :project_after_create
	# before_create :project_before_create
	# around_create :project_around_destroy
	# after_destroy :project_after_destroy
	# #It is considered good practice to declare callback methods as private
	# private       
	# 	def project_after_create
	# 		puts "created successfuly"
	# 	end
	# 	def project_before_create
	# 		puts " creating"
	# 	end
	# 	def project_around_create
	# 		puts "around cheking"
	# 	end
	# 	def project_after_destroy
	# 		puts "deleted successfuly"
	# 	end
	# end	
end

app/models/project_user.rb
class ProjectUser < ApplicationRecord
	belongs_to :project
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_many :project_users
	has_many :projects, through: :project_users
	

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         User_var=  ['developer','manager','qa']
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery

  # protect_from_forgery with: :exception
   before_action :authenticate_user!

   before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :user_type])
  end
  private
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
	def index
    @bug = Bug.all
  end
  def new
        @bug=Bug.new
  end
  
  def create
     @bug=Bug.new(bug_params)
     @bug.creator_id = current_user.id
    if @bug.save!
      redirect_to bugs_path
    else
      redirect_to new_bug
    end
  end
  def edit
     @bug = Bug.find(params[:id])
  end
  def update
     @bug = Bug.find(params[:id])
     if @bug.update_attributes(bug_params)
    
      redirect_to bugs_path
      else
       render 'edit'
      end
  end
  def destroy
     @bug = Bug.find(params[:id])
    if @bug.delete
      redirect_to bugs_path
      end
  end

  def assign
    @bug = Bug.find(params[:id])
    puts @bug.inspect
    puts current_user.inspect
    @bug.update!(developer_id: current_user.id,status:  'started')
    puts @bug.inspect 
    render json: { success: "successful"}
  end

  def assigned
    @bug = Bug.find(params[:id])
    @bug.update!(status: 'complated')
    redirect_to bugs_path
  end
  
  def bug_params   
    params.require(:bug).permit(:title, :deadline, :screenshot, :types, :status, :user_id, :creator_id, :developer_id, :project_id)
  end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
   @project= current_user.projects
  end
  def show
     @project = Project.find(params[:id])
  end
  def new
    @project=Project.new
    @project.project_users.build
    @users = User.all
    @users= User.where. not(user_type: 'manager')
  end
  def create  
    @project=Project.new(project_params)
    authorize @project
    if @project.save!
      @user = ProjectUser.new(project_id: @project.id, user_id: current_user.id)
      @user.save
      redirect_to projects_path
    else
      redirect to new_project_path
    end
  end

  def edit
     @project = Project.find(params[:id])
     @users= User.all
  end   

  def update
     @project = Project.find(params[:id])
     if @project.update_attributes(project_params)
      redirect_to projects_path
      else
        redirect_to edit_project_path
      end
  end
  def destroy
    @userproject = ProjectUser.where(project_id: params[:id]).destroy_all
     @project = Project.find(params[:id])
    if @project.delete
      redirect_to projects_path
      end
  end
  private
  def project_params
     params.require(:project).permit(:id,:name, project_users_attributes:[:id ,:user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bug_helper.rb
module BugHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/bugs/edit.html.erb
<h2>create bug</h2>

<div class="row">
 <div class="col-md-6 col-md-offset-3">
  <%= form_for @bug, url:{action: :update} do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title,class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :deadline %>
    <%= f.date_field :deadline ,class: 'form-control' %>
  </div>

   <div class="field">
    <%= f.label :screenshot %>
    <%= f.file_field :screenshot  %>
  </div> 


  <div class="field ">
     <%= f.label :type %>
     <%= f.select(:types, Bug::TYPE, {} ,class: 'form-control') %>
  </div>

   <div class="field ">
     <%= f.label :status %>
     <%= f.select(:status, Bug::STATUS, {} ,class: 'form-control') %>
  </div>
  <div class="field ">
    <%= f.label :projects %>
  <%= select_tag "projects", options_from_collection_for_select(Project.all, "id", "name"),class: 'form-control' %>
</div>

  <div class="actions">
    <%= f.submit "create new bug", class: "btn btn-primary" %>
  </div>
  <% end %>
 </div>
</div>

app/views/bugs/index.html.erb
<div class="container ">
<table class="table table-hover">
	<thead>
		<tr>
			<th>title</th>
			<th>screenshot</th>
			<th>deadline</th>
			<th>types</th>
			<th>status</th>
		</tr>
	</thead>
	<tbody>
		<% @bug.each do |p|%>
		<tr>
		<td><%= p.title%></td>
		<td><%= image_tag p.screenshot.to_s, :size => '30x30'%></td>
		<td><%= p.deadline%></td>
		<td><%= p.types%></td>
		<td><%= p.status%></td>
		<div>
			<td><%= link_to 'Edit', edit_bug_path(p) %></td>
			<td><%= link_to 'Drop', bug_path(p), method: :delete %></td>
		</div>
	</tr>
		 <% end %>
		 <td><%= link_to 'create', new_bug_path  %></td>
 </tbody>
</table>
</div>

app/views/bugs/new.html.erb
<h2>create bug</h2>

<div class="row">
 <div class="col-md-6 col-md-offset-3">
  <%= form_for @bug, url:{action: :create} do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title,class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :deadline %>
    <%= f.date_field :deadline ,class: 'form-control' %>
  </div>

   <div class="field">
    <%= f.label :screenshot %>
    <%= f.file_field :screenshot  %>
  </div> 


  <div class="field ">
     <%= f.label :type %>
     <%= f.select(:types, Bug::TYPE, {} ,class: 'form-control') %>
  </div>

   <div class="field ">
     <%= f.label :status %>
     <%= f.select(:status, Bug::STATUS, {} ,class: 'form-control') %>
  </div>
  <div class="field ">
    <%= f.label :project %>
     <%= f.collection_select :project_id, Project.all,:id, :name,{}, class: 'form-control' %> 

 </div>
  <div class="actions">
    <%= f.submit "create new bug", class: "btn btn-primary" %>
  </div>
  <% end %>
 </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
	<div class="logo">	<%= link_to "BUGZILLA" %></div>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
				Logged in as <strong><%= current_user.email %></strong>.
                <strong><%= current_user.user_type %></strong>
                <% if (current_user.user_type == "qa") %>
               <li><%= link_to "Bugs", bugs_path, :class => 'navbar-link'  %> | </li>
               <% end %>
                <li> <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>  </li>
				<li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
				</li>
				<% else %>
				<li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> | </li>
                   <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'%></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bugzilla</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <body>
  	<%= render 'layouts/header' %><br><br>
 
    <%= yield %>
  </body>
</html>

app/views/projects/edit.html.erb
<h1>update project</h1>
<div class="row">
<div class="col-md-6 col-md-offset-3">
  <%= form_for @project, url: {action: :update} do |f| %>   
    <%= f.label :name_project %>
    <%= f.text_field :name, class: 'form-control' %>
     <% @users.each do |user| %>
    <%= f.fields_for :project_users do |pu| %>
             <%= pu.label user.name %>          
             <%= pu.check_box :user_id, {}, user.id, nil %>
    <% end %>
<% end %>
    <br>
<%= f.submit  class: "btn btn-primary" %>
<% end %>	
</div>
</div>

app/views/projects/index.html.erb
<div class="container ">
<table class="table table-hover">
	<thead>
		<tr>
			<th>project_name</th>	
		</tr>
	</thead>
	<tbody>

 		<% @project.each do |p| %>
		<tr>
		<td><%= p.name %></td>
		<div>
			<td><%= link_to 'show', project_path(p) %></td>
			<% if policy(@project).edit? %>
			<td><%= link_to 'Edit', edit_project_path(p) %></td>
			<% end %>

			<% if policy(@project).destroy? %>
			<td><%= link_to 'Drop', project_path(p), method: :delete %></td>
			<% end %>
		</div>
	</tr>
		 <% end %>
		 <% if policy(@project).create? %>
		 <td><%= link_to 'create', new_project_path  %></td>
		 <% end %>

  </tbody>
</table>
</div>

app/views/projects/new.html.erb
<h1>create project</h1>
<div class="row">
<div class="col-md-6 col-md-offset-3">

<%= form_for @project do |f| %>
    <%= f.label :name_project %>
    <%= f.text_field :name, class: 'form-control' %>
<% @users.each do |user| %>
    <%= f.fields_for :project_users do |project_user| %>
             <%= project_user.label user.name %>          
             <%= project_user.check_box :user_id, {}, user.id, nil %>
    <% end %>
<% end %>
    <br>
<%= f.submit  class: "btn btn-primary" %>
<% end %>	
</div>
</div>

app/views/projects/show.html.erb
<div>
      <label>Name_user|</label> 
      <% @project.users.each do|u|%>
      <%= u.name %>
      <% end %>
    </div>
     <% if (current_user.user_type == "qa") %>
         <td><%= link_to "add bug", new_bug_path, class: "btn
          btn-primary" %><td>
          <% end %>
    <table class="table table-hover">
      <thead>
        <th>Bugs title </th>
        <th>Type</th>
        <th>Status</th>
        <th>Assign it yourself</th>
      </thead>
      <tbody>
        <div class="col-md-6 col-md-offset-3">
          <tr>
         <% @project.bugs.each do |b| %>
         <td><%= b.title  %></td>
         <td> <%= b.types %></td>
         <td><span id="bug_status_<%= b.id %>" > <%= b.status %></span></td>
         
            <% if (current_user.user_type == "developer") %>
           <%  if (b.developer_id != nil )&& (b.status == "started")&& (current_user.id == b.developer_id)%>
          <td id='<%= b.id %>' >
          <button id="bug_button_<%= b.id %>" data-id="<%= b.id %>" class="btn btn-primary assignme">Mark</button>
                  </td>
            <% elsif  (b.developer_id != nil )&& (b.types == "bug") && (current_user.id == b.developer_id) %>
            <td>resolved</td>
            <% elsif (b.developer_id != nil )&& (b.status == "feature") && (current_user.id == b.developer_id) %>

            <td>completed</td>
            <% elsif (b.developer_id != nil )&& (b.status == "started")|| (b.status == "completed")||(b.status == "resolved")&& (current_user.id != b.developer_id) %>
            <td>assigned</td>
            <% else  %>  
                 <td id='<%= b.id %>' ><button id="bug_button_<%= b.id %>" data-id="<%= b.id %>" class="btn btn-info assignme">Assign me</button></td>
            <% end %>   
            <% end %>
           </tr>
         </div>
          <% end %>
       </tbody>
    </table>
        <%= link_to 'Back', { controller: 'projects', action: 'index'} %>
</div>

<script type="text/javascript">
  $(document).ready(function(){
      $('.assignme').on('click', function(){
         var button = $(this);
         var bugid = this.parentElement.id;
          $.ajax({ 
            url: '/bugs/'+ bugid +'/assign',
            type: "GET",  
            success: function(data){
            button.html("Mark");
           status_id = button.attr("data-id")
           $("#bug_status_"+status_id).html("started")

    $(document).ready(function(){
      $('.assignme').on('click', function(){
         var button = $(this);
         var bugid = this.parentElement.id;
          $.ajax({ 
            url: '/bugs/'+ bugid +'/assigned',
            type: "GET",
            success: function(data){
            button.html("Completed");
            status_id = button.attr("data-id")
            $("#bug_status_"+status_id).html("Completed")
        }
      });
    });
  });

        }
      });
    });
  });
</script>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>